/**
 * QVAC SDK Worker Entry (auto-generated)
 * Generated by: @qvac/sdk/commands bundleSdk
 * Plugins: 2
 *
*   - @qvac/sdk/nmtcpp-translation/plugin
*   - @qvac/sdk/whispercpp-transcription/plugin
 */

import { initializeWorkerCore, ensureRPCSetup } from "file:///home/hickson/tifo/node_modules/@qvac/sdk/dist/server/worker-core.js";
import { registerPlugin } from "file:///home/hickson/tifo/node_modules/@qvac/sdk/dist/server/plugins/index.js";
import { getServerLogger } from "file:///home/hickson/tifo/node_modules/@qvac/sdk/dist/logging/index.js";

import { nmtPlugin } from "file:///home/hickson/tifo/node_modules/@qvac/sdk/dist/server/bare/plugins/nmtcpp-translation/plugin.js";
import { whisperPlugin } from "file:///home/hickson/tifo/node_modules/@qvac/sdk/dist/server/bare/plugins/whispercpp-transcription/plugin.js";

const { hasRPCConfig } = initializeWorkerCore();

const logger = getServerLogger();
logger.info("🐻 QVAC Worker (custom bundle)");
logger.info("📦 Plugins: 2");

registerPlugin(nmtPlugin);
registerPlugin(whisperPlugin);

// Auto-setup RPC if config present
if (hasRPCConfig) {
  ensureRPCSetup();
}
