export const availableRooms = [
  {
    away: 'SEN',
    awayAcc: '#7BC49A',
    awayAccent: '#7BC49A',
    awayName: 'Senegal',
    code: 'MAR-SEN-QF',
    detail: '218 fans',
    fans: 218,
    home: 'MAR',
    homeAcc: '#B87A70',
    homeAccent: '#B87A70',
    homeName: 'Morocco',
    live: true,
    region: 'AFCON · Quarter-final',
    round: 'AFCON · Quarter-final',
    title: 'Morocco vs Senegal',
    tone: 'ignite',
    unread: 0
  },
  {
    away: 'CIV',
    awayAcc: '#D48F5A',
    awayAccent: '#D48F5A',
    awayName: "Côte d'Ivoire",
    code: 'EGY-CIV-R16',
    detail: '154 fans',
    fans: 154,
    home: 'EGY',
    homeAcc: '#B87A70',
    homeAccent: '#B87A70',
    homeName: 'Egypt',
    live: false,
    region: 'AFCON · Round of 16',
    round: 'AFCON · Round of 16',
    title: "Egypt vs Côte d'Ivoire",
    tone: 'warning',
    unread: 0
  },
  {
    away: 'BRA',
    awayAcc: '#D4C25A',
    awayAccent: '#D4C25A',
    awayName: 'Brazil',
    code: 'ARG-BRA-WCQ',
    detail: '892 fans',
    fans: 892,
    home: 'ARG',
    homeAcc: '#7FA6D1',
    homeAccent: '#7FA6D1',
    homeName: 'Argentina',
    live: true,
    region: 'CONMEBOL · WC Qualifier',
    round: 'CONMEBOL · WC Qualifier',
    title: 'Argentina vs Brazil',
    tone: 'cold',
    unread: 12
  },
  {
    away: 'ARS',
    awayAcc: '#B87A70',
    awayAccent: '#B87A70',
    awayName: 'Arsenal',
    code: 'MCI-ARS-PL',
    detail: '621 fans',
    fans: 621,
    home: 'MCI',
    homeAcc: '#7FA6D1',
    homeAccent: '#7FA6D1',
    homeName: 'Man City',
    live: false,
    region: 'Premier League · MW 28',
    round: 'Premier League · MW 28',
    title: 'Man City vs Arsenal',
    tone: 'cold',
    unread: 0
  },
  {
    away: 'BAR',
    awayAcc: '#8B6F9E',
    awayAccent: '#8B6F9E',
    awayName: 'Barcelona',
    code: 'RMA-BAR-EC',
    detail: '1204 fans',
    fans: 1204,
    home: 'RMA',
    homeAcc: '#C7C3BB',
    homeAccent: '#C7C3BB',
    homeName: 'Real Madrid',
    live: false,
    region: 'El Clásico · La Liga',
    round: 'El Clásico · La Liga',
    title: 'Real Madrid vs Barcelona',
    tone: 'clean',
    unread: 0
  }
]
